version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: users-mongo
    restart: unless-stopped
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: